name: flutter_state
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.0-154.0.dev <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  mobx_codegen: ^2.0.5+2
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
 






flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
